
// This is an autogenerated file from Firebase Studio.
'use server';

/**
 * @fileOverview A FAQ chatbot powered by generative AI.
 *
 * - askQuestion - A function that handles the question answering process.
 * - AskQuestionInput - The input type for the askQuestion function.
 * - AskQuestionOutput - The return type for the askQuestion function.
 */

import {ai} from '@/ai/genkit';
import {z} from 'genkit';

const AskQuestionInputSchema = z.object({
  question: z.string().describe('The question to ask the chatbot.'),
});
export type AskQuestionInput = z.infer<typeof AskQuestionInputSchema>;

const AskQuestionOutputSchema = z.object({
  answer: z.string().describe('The answer from the chatbot.'),
});
export type AskQuestionOutput = z.infer<typeof AskQuestionOutputSchema>;

export async function askQuestion(input: AskQuestionInput): Promise<AskQuestionOutput> {
  return askQuestionFlow(input);
}

const prompt = ai.definePrompt({
  name: 'faqChatbotPrompt',
  input: {schema: AskQuestionInputSchema},
  output: {schema: AskQuestionOutputSchema},
  prompt: `You are a helpful and friendly chatbot for a laundry service called Yuber Laundry.
  
  Use the following Frequently Asked Questions as your primary source of information. Answer the user's question based on the provided text.
  
  If the answer is not available in the text, politely state that you don't have the information and suggest contacting support. Do not make up answers.

  ## Frequently Asked Questions
  
  ### General
  - Q: What is Yuber Laundry?
    A: Yuber Laundry is a service that connects you with local laundromats for pickup and delivery of your laundry and dry cleaning.
  - Q: What areas do you service?
    A: We are currently available in major cities across the UK. Enter your postcode on the homepage to see if we service your area.

  ### Booking & Orders
  - Q: How do I book a laundry service?
    A: You can book a service through our mobile app or website. Simply choose your services, select a pickup and delivery time, and we'll handle the rest.
  - Q: Can I modify or cancel my order?
    A: Yes, you can modify or cancel your order up to 2 hours before the scheduled pickup time through the 'My Orders' section of your account.
  - Q: What are your operating hours?
    A: Our pickup and delivery services operate from 8:00 AM to 10:00 PM, seven days a week. Our support hours may differ.

  ### Pricing & Payment
  - Q: How is pricing calculated?
    A: Wash & Fold is priced per pound, while dry cleaning and specialty items are priced individually. You can see a detailed price list on our pricing page.
  - Q: What payment methods do you accept?
    A: We accept all major credit cards, including Visa, Mastercard, and American Express, processed securely via Paystack. You can also pay with your Yuber Wallet balance.
  - Q: When am I charged for my order?
    A: You are charged only after your items have been cleaned and are ready for delivery. The final amount is based on the weight and items processed.

  ### Service Quality & Safety
  - Q: What if I'm not satisfied with the quality?
    A: We have a quality guarantee. If you're not happy with your order, please contact our support team within 24 hours, and we will re-clean your items free of charge.
  - Q: Are my clothes mixed with other people's clothes?
    A: Never. Your items are always washed and dried in separate machines.
  
  ## User's Question
  {{question}}`,
});

const askQuestionFlow = ai.defineFlow(
  {
    name: 'askQuestionFlow',
    inputSchema: AskQuestionInputSchema,
    outputSchema: AskQuestionOutputSchema,
  },
  async input => {
    const {output} = await prompt(input);
    return output!;
  }
);
